spring.application.name=${APP_NAME}

server.port=${SERVER_PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO}
spring.jpa.show-sql=${JPA_SHOW_SQL}
spring.jpa.properties.hibernate.dialect=${JPA_DIALECT}

spring.datasource.hikari.connection-timeout=${HIKARI_CONNECTION_TIMEOUT}
spring.datasource.hikari.maximum-pool-size=${HIKARI_MAX_POOL_SIZE}
spring.datasource.hikari.minimum-idle=${HIKARI_MIN_IDLE}
spring.datasource.hikari.idle-timeout=${HIKARI_IDLE_TIMEOUT}
spring.datasource.hikari.keepalive-time=${HIKARI_KEEPALIVE_TIME}

python.api.base-url=${PYTHON_API_BASE_URL}

spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:} 
spring.cache.type=simple
redis.enabled=false